In [ ]:
from utils.constantes import DATA_CLEAN_PATH
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [53]:
def nombre_aglomerado(codigo):
    """
    Devuelve el nombre del aglomerado a partir de su código.

    Args:
        codigo (str): Código del aglomerado.

    Returns:
        str or None: Nombre del aglomerado o None si no existe.
    """
    dic_aglomerados = {
        '2': 'Gran La Plata',
        '3': 'Bahía Blanca - Cerri',
        '4': 'Gran Rosario',
        '5': 'Gran Santa Fé',
        '6': 'Gran Paraná',
        '7': 'Posadas',
        '8': 'Gran Resistencia',
        '9': 'Comodoro Rivadavia - Rada Tilly',
        '10': 'Gran Mendoza',
        '12': 'Corrientes',
        '13': 'Gran Córdoba',
        '14': 'Concordia',
        '15': 'Formosa',
        '17': 'Neuquén - Plottier',
        '18': 'Santiago del Estero - La Banda',
        '19': 'Jujuy - Palpalá',
        '20': 'Río Gallegos',
        '22': 'Gran Catamarca',
        '23': 'Gran Salta',
        '25': 'La Rioja',
        '26': 'Gran San Luis',
        '27': 'Gran San Juan',
        '29': 'Gran Tucumán - Tafí Viejo',
        '30': 'Santa Rosa - Toay',
        '31': 'Ushuaia - Río Grande',
        '32': 'Ciudad Autónoma de Buenos Aires',
        '33': 'Partidos del GBA',
        '34': 'Mar del Plata',
        '36': 'Río Cuarto',
        '38': 'San Nicolás - Villa Constitución',
        '91': 'Rawson - Trelew',
        '93': 'Viedma - Carmen de Patagones'
    }
    return dic_aglomerados.get(codigo)

In [30]:
archivo_clean_path = DATA_CLEAN_PATH / "usu_clean_individual.csv"
df = pd.read_csv(archivo_clean_path, delimiter=",",low_memory=False)
df = df[df["ANO4"] == 2024]
df = df[df["TRIMESTRE"] == 2]
df

,CODUSU,ANO4,TRIMESTRE,NRO_HOGAR,COMPONENTE,H15,REGION,MAS_500,AGLOMERADO,PONDERA,...,IDECCFR,RDECCFR,GDECCFR,PDECCFR,ADECCFR,PONDIH,CH04_str,NIVEL_ED_str,CONDICION_LABORAL,UNIVERSITARIO
46050,TQRMNORUUHJLMRCDEIIAD00861800,2024,2,1,2,1,1,S,32,2678,...,NaN,8,8.0,NaN,6,4604,femenino,superior o universitario,inactivo,1
46051,TQRMNORPRHKLMUCDEIIAD00858515,2024,2,1,1,1,1,S,32,2912,...,NaN,8,8.0,NaN,6,3713,femenino,superior o universitario,ocupado dependiente,1
46052,TQRMNORPRHKLMUCDEIIAD00858515,2024,2,1,2,1,1,S,32,2912,...,NaN,8,8.0,NaN,6,3713,femenino,superior o universitario,ocupado dependiente,1
46053,TQRMNORPRHKLMUCDEIIAD00858515,2024,2,1,3,1,1,S,32,2912,...,NaN,8,8.0,NaN,6,3713,femenino,secundario incompleto,inactivo,2
46054,TQRMNOSSUHKLMUCDEIIAD00858728,2024,2,1,1,1,1,S,32,1519,...,NaN,12,12.0,NaN,12,0,femenino,superior o universitario,ocupado dependiente,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93196,TQRMNORQQHJLLMCDEGKDB00866867,2024,2,1,3,0,43,N,14,152,...,6.0,5,NaN,7.0,7,489,masculino,sin informacion,fuera de categoria,0
93197,TQRMNORQQHJLLMCDEGKDB00866867,2024,2,1,4,0,43,N,14,152,...,6.0,5,NaN,7.0,7,489,femenino,primario incompleto,fuera de categoria,0
93198,TQRMNORRTHJKLNCDEGKDB00866868,2024,2,1,1,1,43,N,14,174,...,8.0,7,NaN,8.0,9,283,femenino,primario completo,inactivo,0
93199,TQSMNOPYSHMOKMCDEFMDB00866869,2024,2,1,1,1,43,N,6,183,...,3.0,2,NaN,3.0,2,272,femenino,secundario incompleto,ocupado dependiente,0
93200,TQSMNOPYSHMOKMCDEFMDB00866869,2024,2,1,2,1,43,N,6,183,...,3.0,2,NaN,3.0,2,272,masculino,primario completo,inactivo,0

In [31]:
df['PP09A_ESP'] = df['PP09A_ESP'].fillna(0)
df['PP09A_ESP']

46050    0
46051    0
46052    0
46053    0
46054    0
        ..
93196    0
93197    0
93198    0
93199    0
93200    0
Name: PP09A_ESP, Length: 47151, dtype: object

In [32]:
df_anios =  sorted(df["ANO4"].astype(str).unique())
df_trimestres = sorted(df['TRIMESTRE'].astype(str).unique())
# anio_seleccionado = todos

In [ ]:
# df con columnas de edad y sexo 
df_filtrado = df[["PONDERA","CH04", "CH06"]].copy()


rango_anios = range(0,101,10)
etiquetas =  [f"{i}-{i+9}" for i in rango_anios[:-1]] 

df_filtrado["CH06"] = pd.to_numeric(df_filtrado["CH06"], errors="coerce")
df_filtrado["grupos_edad"] = pd.cut(df_filtrado["CH06"],bins=rango_anios , labels=etiquetas)

df_filtrado["CH04"] = df_filtrado["CH04"].apply(lambda x: "M" if x == 1 else "F")
df_filtrado = df_filtrado.groupby(["CH04","grupos_edad"])["PONDERA"].sum().reset_index()

df_filtrado

C:\Users\Usuario\AppData\Local\Temp\ipykernel_18088\1876331794.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_filtrado = df_filtrado.groupby(["CH04","grupos_edad"])["PONDERA"].sum().reset_index()

   CH04 grupos_edad  PONDERA
0     F         0-9  2104948
1     F       10-19  2378439
2     F       20-29  2170358
3     F       30-39  2116476
4     F       40-49  2018796
5     F       50-59  1557663
6     F       60-69  1351334
7     F       70-79   959103
8     F       80-89   368272
9     F       90-99    65092
10    M         0-9  2218035
11    M       10-19  2578370
12    M       20-29  2097435
13    M       30-39  1985981
14    M       40-49  1973348
15    M       50-59  1522848
16    M       60-69  1087231
17    M       70-79   659582
18    M       80-89   201966
19    M       90-99    17062

In [35]:
df_hombres = df_filtrado[df_filtrado["CH04"] == 'M'].copy()
df_mujeres = df_filtrado[df_filtrado["CH04"] == 'F'].copy()
df_pivot = df_filtrado.pivot(index="grupos_edad",columns="CH04",values="PONDERA")
df_pivot

CH04               F        M
grupos_edad
0-9          2104948  2218035
10-19        2378439  2578370
20-29        2170358  2097435
30-39        2116476  1985981
40-49        2018796  1973348
50-59        1557663  1522848
60-69        1351334  1087231
70-79         959103   659582
80-89         368272   201966
90-99          65092    17062

In [ ]:
x = np.arange(len(df_hombres.index))
ancho = 0.35 
valores_y = [0,1000000,2000000,3000000,4000000,5000000]
labels_y = ["0","1.000.000","2.000.000","3.000.000","4.000.000","5.000.000"]

fig, ax = plt.subplots()

ax.bar(x - ancho / 2 , df_hombres["PONDERA"], width=ancho , label="hombres")
ax.bar(x + ancho / 2 , df_mujeres["PONDERA"], width=ancho , label="mujeres")

ax.set_xlabel("grupos por edad") 
ax.set_ylabel("cantidad de gente") 


ax.set_xticklabels(df_hombres["grupos_edad"])
ax.set_yticklabels(labels_y)
ax.legend()

In [42]:
ultimo_anio = int(df["ANO4"].unique().max())
df_ult_anio = df[df["ANO4"] == ultimo_anio]
ultimo_trim = int(df_ult_anio["TRIMESTRE"].unique().max())
df_reciente = df_ult_anio[df_ult_anio["TRIMESTRE"] == ultimo_trim]

In [68]:
df_aglomerado = df_ult_anio[["AGLOMERADO","CH06"]].copy()
df_aglomerado['nombre_aglomerado'] = df_aglomerado['AGLOMERADO'].astype(str).apply(nombre_aglomerado)
df_aglomerado = df_aglomerado.groupby(["AGLOMERADO","nombre_aglomerado"]).mean("CH06")
df_aglomerado['CH06'] = df_aglomerado['CH06'].round(2)
df_aglomerado

                                              CH06
AGLOMERADO nombre_aglomerado
2          Gran La Plata                     35.37
3          Bahía Blanca - Cerri              36.75
4          Gran Rosario                      36.69
5          Gran Santa Fé                     36.10
6          Gran Paraná                       38.75
7          Posadas                           35.34
8          Gran Resistencia                  34.71
9          Comodoro Rivadavia - Rada Tilly   34.65
10         Gran Mendoza                      37.13
12         Corrientes                        36.34
13         Gran Córdoba                      34.57
14         Concordia                         34.65
15         Formosa                           36.96
17         Neuquén - Plottier                36.86
18         Santiago del Estero - La Banda    33.50
19         Jujuy - Palpalá                   35.28
20         Río Gallegos                      37.27
22         Gran Catamarca                    33.85
23         Gran Salta                        35.33
25         La Rioja                          34.37
26         Gran San Luis                     36.33
27         Gran San Juan                     35.46
29         Gran Tucumán - Tafí Viejo         34.62
30         Santa Rosa - Toay                 38.46
31         Ushuaia - Río Grande              35.66
32         Ciudad Autónoma de Buenos Aires   41.92
33         Partidos del GBA                  36.89
34         Mar del Plata                     37.51
36         Río Cuarto                        37.57
38         San Nicolás - Villa Constitución  36.16
91         Rawson - Trelew                   37.29
93         Viedma - Carmen de Patagones      37.30

Dependencia demográfica = ((Población de 0 a 14 años + Población de 65 años o más) / Población de 15 a 64 años ) * 100

In [90]:
aglo_seleccionado = 32

In [116]:
df_activos = df[(df["AGLOMERADO"] == aglo_seleccionado) & (df["CH06"].between(15,64,inclusive="both")) ][["AGLOMERADO","CH06","PONDERA"]].copy()
df_not_activos = df[(df["AGLOMERADO"] == aglo_seleccionado) & ( ~df["CH06"].between(15,64,inclusive="both")) ][["AGLOMERADO","CH06","PONDERA"]].copy()

df_activos = df_activos.groupby(["AGLOMERADO"]).sum("PONDERA")
df_not_activos = df_not_activos.groupby(["AGLOMERADO"]).sum("PONDERA")

df_not_activos["grupo"] = "no activos"
df_activos["grupo"] = "activos"

df_union = pd.concat([df_not_activos, df_activos])
df_union

             CH06  PONDERA       grupo
AGLOMERADO
32          19570  1086208  no activos
32          38578  1919267     activos